name: DEV

on:
  push:
    branches:
      - dev

jobs:
  server:
    name: Deploy server
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Save private key
        run: |
          mkdir ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{secrets.SERVER_HOST}} >> ~/.ssh/known_hosts
      - name: Deploy code to server
        run: rsync -av --delete ./ ${{secrets.SERVER_USER}}@${{secrets.SERVER_HOST}}:${{secrets.SERVER_ROOT}}
      - name: Install dependencies on server
        run: ssh ${{secrets.SERVER_USER}}@${{secrets.SERVER_HOST}} "cd ${{secrets.SERVER_ROOT}} && npm install"
      - name: Stop server
        run: ssh ${{secrets.SERVER_USER}}@${{secrets.SERVER_HOST}} "cd ${{secrets.SERVER_ROOT}} && npx pm2 stop ${{secrets.SERVER_NAME}}"
      - name: Start server
        run: ssh ${{secrets.SERVER_USER}}@${{secrets.SERVER_HOST}} "cd ${{secrets.SERVER_ROOT}} && npx pm2 start server/index.js --name ${{secrets.SERVER_NAME}}"